services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  postgres_db:
    container_name: postgres_db
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=blog_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    depends_on:
      - redis
      - postgres_db
    build:
      context: .
      dockerfile: ./dockerfiles/dev/Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./core:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    env_file:
      - env/prod/.env
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn BlogSite.wsgi --bind 0.0.0.0:8000"
    restart: unless-stopped

  worker:
    depends_on:
      - redis
      - postgres_db
      - backend
    build:
      context: .
      dockerfile: ./dockerfiles/dev/Dockerfile
    container_name: worker
    volumes:
      - ./core:/usr/src/app
    env_file:
      - env/prod/.env
    command: sh -c "celery -A BlogSite worker --loglevel=info"
    restart: unless-stopped

  beat:
    depends_on:
      - redis
      - postgres_db
      - backend
    build:
      context: .
      dockerfile: ./dockerfiles/dev/Dockerfile
    container_name: beat
    volumes:
      - ./core:/usr/src/app
    env_file:
      - env/dev/.env
    command: sh -c "celery -A BlogSite beat --loglevel=info"
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    depends_on:
      - backend
      - redis

volumes:
  postgres_data:
  static_volume:
  media_volume: