# Generated by Django 5.2.4 on 2025-07-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_token", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="token",
            old_name="is_active",
            new_name="_is_active",
        ),
    ]
