# Generated by Django 5.2.3 on 2025-06-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="users", verbose_name="Profile Image"),
        ),
    ]
