name: Django Project Test and Reformat

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
  Reformat:
    runs-on: ubuntu-latest
    name: Reformat
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
          
        - name: Copy .env.sample
          run: cp env/dev/.env.sample env/dev/.env

        - name: Setup docker compose
          run: docker compose -f docker-compose-dev.yml up -d

        - name: Reformat and flake8 check
          run: docker compose -f docker-compose-dev.yml exec backend sh -c "black --line-length 120 . && flake8 ."

  Test:
    runs-on: ubuntu-latest
    name: Test
    needs: Reformat
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
          
        - name: Copy .env.sample
          run: cp env/dev/.env.sample env/dev/.env

        - name: Setup docker compose
          run: docker compose -f docker-compose-dev.yml up -d
        
        - name: Run tests
          run: docker compose -f docker-compose-dev.yml exec backend sh -c "pytest ."        